void menu();
void load();
void Add();
void Save();
void Delete(int x);
void Quit();
void modify(int z);
void Sort();
void sortByDOB();
void sortByLname();
void sortByFname();
void Search(char c,int* found);
void inttostr(int* found,char c);
int substring(char* m,char* s);
void Multisearch(int* found);
void menulist();
void searchlist();
void modifylist();
void sortlist();
void printdir(directory z,int i);
void printfound(int* found);
int counter();
void fillzero(int* a,int x);
void fillone(int* a,int x);
void Shift(int i,int j);
void Swap(int i,int j);
int zerocheck(int* found,int x);
int validateemail(char* e);
int validatedate(int d,int m,int y);
int validatename(char* n);
int validatenumber(char* n);
void charcheck(char* c);
